---
sample_name: 'Sample_ID' #setup2_organize - if your fastq file is already concatenated, paste all text preceding '.fastq.gz' into sample_name
input_files:
  setup:
    - general_path: '/path/to/Pipeline_Folder_Name'
  all:
    input_data: '/projects/sperolab/kenlai/test_data_barcode_map' #setup2_organize
  samples:
    - sample1_R1: '/path/to/sample1_R1.fastq.gz'
    - sample2_R1: '/path/to/sample2_R1.fastq.gz'
  reference:
    - genome_fasta: 'path/to/genome.fa'
    - annotation_gtf: 'path/to/refgenome.gtf'
adjustable_parameters:
  input_data:
    fastq_cat: yes #setup2_organize
  QC:
    - mismatch_threshold: 3
    - phredscore_cutoff: 25 
  CPUs:
    - default: 4
    - bowtie2: 8 
    - fastqc: 2
  RAM:
  Time:
